name: Deployment

on:
  push:

jobs:
  publish-conda-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda config --add channels paulscherrerinstitute
        $CONDA/bin/conda config --add channels nodefaults
        $CONDA/bin/conda install --quiet --yes conda-build anaconda-client
