name: Deployment

on:
  push:

jobs:
  publish-conda-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        channels: paulscherrerinstitute, conda-forge
        conda-remove-defaults: true
        activate-environment: ""

    - name: Debug
      run: |
        conda list

    - name: Prepare
      run: |
        conda install --quiet --yes conda-build anaconda-client

    - name: Debug2
      run: |
        anaconda -h
